"""Execute the pytest suite generated by the most recent pipeline run.

The QA crew *generates* pytest automation; it does not execute it, because
execution needs a warehouse. This script closes that loop for the demo: it
runs the latest generated suite against the deterministic demo SQLite
database and prints real pass/fail results.

    python scripts/run_generated_tests.py [RUN_DIR]

``RUN_DIR`` defaults to the most recent ``outputs/RUN-*`` directory. The
script sets ``ETL_TEST_DATABASE_URL`` to the demo SQLite database
(``outputs/hc_etl_demo.db``) which ``build_fixtures.py`` materialises from the
same rows the agents analysed.

Note on dialect: generated suites may target a warehouse dialect (the demo
run emits ``information_schema.columns``, which is PostgreSQL). SQLite has no
``information_schema``, so schema-introspection tests are translated to
``PRAGMA table_info`` before execution. Row-count and value tests run
unchanged. This keeps the demo self-contained and honest.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEMO_DB = ROOT / "outputs" / "hc_etl_demo.db"

#: Generated suites routinely use PostgreSQL's information_schema for the
#: schema-introspection test. SQLite exposes the same data through PRAGMA.
#: The translation keeps the demo executable on the local database.
_INFORMATION_SCHEMA_RE = re.compile(
    r"SELECT\s+COUNT\(\*\)\s+FROM\s+information_schema\.columns\s+"
    r"WHERE\s+table_name\s*=\s*:table",
    re.IGNORECASE,
)
_PRAGMA_SQL = "SELECT COUNT(*) FROM pragma_table_info(:table)"


def _translate_to_sqlite(content: str) -> str:
    """Rewrite PostgreSQL-only introspection SQL into SQLite PRAGMA calls."""
    return _INFORMATION_SCHEMA_RE.sub(_PRAGMA_SQL, content)


def _run_dir_for(target: str | None) -> Path:
    if target:
        candidate = Path(target)
        if not candidate.is_dir():
            sys.exit(f"Run directory not found: {candidate}")
        return candidate
    runs = sorted(ROOT.glob("outputs/RUN-*"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not runs:
        sys.exit("No outputs/RUN-* directories found. Run scripts/demo_smoke.py first.")
    return runs[0]


def _find_pytest_tests(run_dir: Path) -> Path | None:
    for path in run_dir.rglob("pytest/tests/test_*.py"):
        return path.parent
    return None


def main(argv: list[str]) -> int:
    if not DEMO_DB.exists():
        print(f"Demo database not found at {DEMO_DB}. Building it now...")
        subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "build_fixtures.py")],
            check=True,
            cwd=ROOT,
        )

    run_dir = _run_dir_for(argv[0] if argv else None)
    tests_dir = _find_pytest_tests(run_dir)
    if tests_dir is None:
        print(f"No generated pytest found under {run_dir}. Run scripts/demo_smoke.py first.")
        return 2

    print(f"Run:       {run_dir.name}")
    print(f"Test suite: {tests_dir.relative_to(run_dir)}")
    print(f"Database:  {DEMO_DB}")

    test_file = next(tests_dir.glob("test_*.py"))
    original = test_file.read_text(encoding="utf-8")
    translated = _translate_to_sqlite(original)
    if translated != original:
        test_file.write_text(translated, encoding="utf-8")
        print("Note: translated information_schema queries to SQLite PRAGMA "
              "so the suite can run on the demo database.")

    env = os.environ.copy()
    env["ETL_TEST_DATABASE_URL"] = f"sqlite:///{DEMO_DB}"
    result = subprocess.run(
        [sys.executable, "-m", "pytest", str(tests_dir), "-v"],
        cwd=ROOT,
        env=env,
    )

    # Restore the pristine generated file so re-runs translate deterministically.
    if translated != original:
        test_file.write_text(original, encoding="utf-8")

    print(f"\nExit code: {result.returncode}")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
