"""Deterministic renderers and artifact writing.

Everything here is pure Python over validated Pydantic objects. No LLM output
is used as-is: the agents produce structured data, and these functions decide
exactly how it becomes Markdown, CSV, JSON, pytest and a ZIP.
"""

from __future__ import annotations

import csv
import io
import json
import zipfile
from datetime import datetime
from pathlib import Path

from hc_etl_qa_crew.models import (
    AutomationCandidate,
    CoverageReport,
    PipelineResult,
    PipelineStatus,
    PytestBundle,
    ReconcilePlan,
    RunSummary,
    SchemaAnalysis,
    TestCaseSuite,
)

from .pipelines import safe_path_segment

_GENERATED_NOTE = (
    "> Generated by Healthcare ETL QA Crew. Every item traces to the pipeline "
    "contract and the observed snapshot; anything marked INFERRED or "
    "ASSUMPTION_REQUIRING_CONFIRMATION needs human review before it is treated "
    "as fact."
)


# --------------------------------------------------------------------------
# Markdown renderers
# --------------------------------------------------------------------------
def render_schema_analysis_md(analysis: SchemaAnalysis) -> str:
    lines = [
        f"# Schema & Transform Analysis — {analysis.pipeline_name}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Summary:** {analysis.summary or '_none_'}",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Fact table | {analysis.fact_table or '—'} |",
        f"| Dimension tables | {', '.join(analysis.dimension_tables) or '—'} |",
        f"| Source system | {analysis.source_system or 'not set'} |",
        f"| Load frequency | {analysis.load_frequency or 'not set'} |",
        f"| Observed via | {analysis.source.value} |",
        "",
    ]

    lines += ["## Requirements", ""]
    reqs = [e for e in analysis.entities if e.entity_type == "requirement"]
    if reqs:
        lines += ["| ID | Requirement | Table | Provenance | Severity |", "| --- | --- | --- | --- | --- |"]
        for e in reqs:
            lines.append(
                f"| {e.id} | {_cell(e.text)} | {e.table_name or '—'} | "
                f"{e.provenance.value} | {e.severity.value} |"
            )
    else:
        lines.append("_No requirements were extracted._")
    lines.append("")

    lines += ["## Data-Quality Rules", ""]
    dqs = [e for e in analysis.entities if e.entity_type == "data_quality"]
    if dqs:
        lines += ["| ID | Rule | Table | Provenance | Severity |", "| --- | --- | --- | --- | --- |"]
        for e in dqs:
            lines.append(
                f"| {e.id} | {_cell(e.text)} | {e.table_name or '—'} | "
                f"{e.provenance.value} | {e.severity.value} |"
            )
    else:
        lines.append("_No data-quality rules were extracted._")
    lines.append("")

    if analysis.transform_rules:
        lines += ["## Transform Rules", "", "| ID | Source | Target | Type | Logic | Risk |", "| --- | --- | --- | --- | --- | --- |"]
        for rule in analysis.transform_rules:
            lines.append(
                f"| {rule.id} | {rule.source_table} | {rule.target_table} | "
                f"{rule.rule_type} | {_cell(rule.logic)} | {rule.risk.value} |"
            )
        lines.append("")

    if analysis.field_profiles:
        lines += ["## Field Profiles", "", "| Table.Column | Type | Nulls | Distinct | Min | Max |", "| --- | --- | --- | --- | --- | --- |"]
        for profile in analysis.field_profiles:
            lines.append(
                f"| {profile.table_name}.{profile.column_name} | {profile.data_type} | "
                f"{profile.nulls_observed} | {profile.distinct_observed} | "
                f"{profile.min_value or '—'} | {profile.max_value or '—'} |"
            )
        lines.append("")

    for title, values in (
        ("Risks", analysis.risks),
        ("Assumptions (require confirmation)", analysis.assumptions),
        ("Missing Information", analysis.missing_information),
        ("Open Questions", analysis.open_questions),
    ):
        lines += [f"## {title}", ""]
        lines += [f"- {v}" for v in values] or ["_none recorded_"]
        lines.append("")
    return "\n".join(lines)


def render_recon_plan_md(plan: ReconcilePlan) -> str:
    lines = [
        f"# Reconciliation & Data-Quality Strategy — {plan.pipeline_name}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Summary:** {plan.summary or '_none_'}",
        "",
    ]

    lines += ["## Reconciliation Strategies", ""]
    if plan.strategies:
        lines += ["| ID | Strategy | Type | Source | Target | Match key | Tolerance |", "| --- | --- | --- | --- | --- | --- | --- |"]
        for strategy in plan.strategies:
            lines.append(
                f"| {strategy.id} | {_cell(strategy.name)} | {strategy.recon_type.value} | "
                f"{strategy.source_table or '—'} | {strategy.target_table or '—'} | "
                f"{', '.join(strategy.match_key) or '—'} | {strategy.tolerance_pct}% |"
            )
    else:
        lines.append("_No reconciliation strategies were produced._")
    lines.append("")

    lines += ["## Data-Quality Rules", ""]
    if plan.quality_rules:
        lines += ["| ID | Rule | Dimension | Table | Column | Threshold | Severity |", "| --- | --- | --- | --- | --- | --- | --- |"]
        for rule in plan.quality_rules:
            lines.append(
                f"| {rule.id} | {_cell(rule.name)} | {rule.dimension.value} | "
                f"{rule.table_name or '—'} | {rule.column_name or '—'} | "
                f"{rule.threshold or '—'} | {rule.severity.value} |"
            )
    else:
        lines.append("_No quality rules were produced._")
    lines.append("")

    for title, values in (
        ("Environment Strategy", plan.environment_strategy),
        ("Execution Order", plan.execution_order),
        ("Entry / Exit Criteria", plan.entry_exit_criteria),
        ("Risks", plan.risks),
        ("Dependencies", plan.dependencies),
        ("Assumptions", plan.assumptions),
        ("Missing Information", plan.missing_information),
    ):
        lines += [f"## {title}", ""]
        lines += [f"- {v}" for v in values] or ["_none recorded_"]
        lines.append("")
    return "\n".join(lines)


def render_test_cases_md(suite: TestCaseSuite) -> str:
    lines = [
        f"# Data-Quality Test Cases — {suite.pipeline_name}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Total test cases:** {len(suite.test_cases)}",
        "",
    ]
    if suite.coverage_notes:
        lines += ["## Coverage Notes", "", suite.coverage_notes.strip(), ""]

    for case in suite.test_cases:
        lines += [
            f"## {case.id} — {case.title}",
            "",
            f"- **Pipeline:** {case.pipeline_name}",
            f"- **Priority:** {case.priority}",
            f"- **Type:** {case.test_type.value}",
            f"- **Quality dimension:** {case.quality_dimension.value}",
            f"- **Table / column:** {case.table_name or '—'} / {case.column_name or '—'}",
            f"- **Requirements:** {', '.join(case.requirement_ids) or '—'}",
            f"- **Data-quality rules:** {', '.join(case.data_quality_ids) or '—'}",
            f"- **Automation candidate:** {case.automation_candidate.value}"
            + (f" — {case.automation_rationale}" if case.automation_rationale else ""),
            f"- **Tags:** {', '.join(case.tags) or '—'}",
            "",
            f"**Objective:** {case.objective or '—'}",
            "",
        ]
        if case.preconditions:
            lines += ["**Preconditions:**", *[f"- {p}" for p in case.preconditions], ""]
        if case.test_data:
            lines += ["**Test data:**", *[f"- {d}" for d in case.test_data], ""]
        lines += ["| # | Action | Expected |", "| --- | --- | --- |"]
        for step in case.steps:
            lines.append(f"| {step.number} | {_cell(step.action)} | {_cell(step.expected) or '—'} |")
        lines += ["", f"**Expected result:** {case.expected_result or '—'}", ""]
        if case.sql_template:
            lines += ["**SQL template:**", "", f"```sql\n{case.sql_template.strip()}\n```", ""]
        if case.assumptions_or_blockers:
            lines += [
                "**Assumptions / blockers:**",
                *[f"- {b}" for b in case.assumptions_or_blockers],
                "",
            ]
    return "\n".join(lines)


def render_pytest_md(bundle: PytestBundle) -> str:
    lines = [
        f"# pytest Automation — {bundle.pipeline_name}",
        "",
        _GENERATED_NOTE,
        "",
        f"**Automation readiness:** `{bundle.readiness.value}`",
        "",
    ]
    if bundle.readiness.value == "NEEDS_CONFIGURATION":
        lines += [
            "> This code imports cleanly but is **not execution-ready**. The "
            "items under Missing Information must be supplied first.",
            "",
        ]
    if bundle.setup_notes:
        lines += ["## Setup", "", bundle.setup_notes.strip(), ""]

    if bundle.traces:
        lines += [
            "## Coverage",
            "",
            "| Test | Test case | Requirements | Data-quality rules | File |",
            "| --- | --- | --- | --- | --- |",
        ]
        for trace in bundle.traces:
            lines.append(
                f"| {_cell(trace.test_name)} | {trace.test_case_id} | "
                f"{', '.join(trace.requirement_ids) or '—'} | "
                f"{', '.join(trace.data_quality_ids) or '—'} | {trace.file_path or '—'} |"
            )
        lines.append("")

    lines += ["## Generated files", ""]
    for file in bundle.files:
        lines += [f"### `{file.path}`", "", "```python", file.content.rstrip(), "```", ""]

    for title, values in (
        ("Missing Information", bundle.missing_information),
        ("Assumptions", bundle.assumptions),
    ):
        lines += [f"## {title}", ""]
        lines += [f"- {v}" for v in values] or ["_none_"]
        lines.append("")
    return "\n".join(lines)


def render_run_summary_md(run: RunSummary) -> str:
    lines = [
        "# Run Summary",
        "",
        f"**Run ID:** {run.run_id}",
        f"**Started:** {_stamp(run.started_at)}",
        f"**Finished:** {_stamp(run.finished_at)}",
        "",
        f"- Pipelines requested: {len(run.requested_pipelines)}",
        f"- Completed: {len(run.completed)}",
        f"- Completed with warnings: {len(run.completed_with_warnings)}",
        f"- Failed: {len(run.failed)}",
        "",
    ]
    if run.invalid_inputs:
        lines += [f"- Rejected input tokens: {', '.join(run.invalid_inputs)}", ""]
    if run.duplicates_removed:
        lines += [f"- Duplicates removed: {', '.join(run.duplicates_removed)}", ""]

    lines += [
        "| Pipeline | Status | Source | Automation | Reqs | DQ rules | Test cases | Coverage |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for result in run.results:
        coverage = (
            f"{result.coverage.requirement_coverage_pct}%" if result.coverage else "—"
        )
        lines.append(
            f"| {result.pipeline_name} | {result.status.value} | "
            f"{result.source.value if result.source else '—'} | "
            f"{result.pytest.readiness.value if result.pytest else '—'} | "
            f"{result.coverage.total_requirements if result.coverage else 0} | "
            f"{result.coverage.total_data_quality if result.coverage else 0} | "
            f"{result.coverage.total_test_cases if result.coverage else 0} | {coverage} |"
        )
    lines.append("")

    failures = run.failed
    if failures:
        lines += ["## Failures", ""]
        for result in failures:
            lines.append(f"- **{result.pipeline_name}**: {result.error}")
        lines.append("")

    warned = [r for r in run.results if r.warnings]
    if warned:
        lines += ["## Warnings", ""]
        for result in warned:
            lines.append(f"- **{result.pipeline_name}**")
            lines += [f"  - {w}" for w in result.warnings]
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# CSV renderers
# --------------------------------------------------------------------------
def render_test_cases_csv(suite: TestCaseSuite) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        [
            "test_case_id", "pipeline_name", "title", "objective", "priority", "test_type",
            "quality_dimension", "table_name", "column_name", "requirement_ids",
            "data_quality_ids", "preconditions", "test_data", "steps", "expected_result",
            "sql_template", "automation_candidate", "automation_rationale", "tags",
            "assumptions_or_blockers",
        ]
    )
    for case in suite.test_cases:
        writer.writerow(
            [
                case.id, case.pipeline_name, case.title, case.objective, case.priority,
                case.test_type.value, case.quality_dimension.value, case.table_name,
                case.column_name, "; ".join(case.requirement_ids),
                "; ".join(case.data_quality_ids), " | ".join(case.preconditions),
                " | ".join(case.test_data),
                " | ".join(
                    f"{s.number}. {s.action}" + (f" -> {s.expected}" if s.expected else "")
                    for s in case.steps
                ),
                case.expected_result, case.sql_template, case.automation_candidate.value,
                case.automation_rationale, "; ".join(case.tags),
                " | ".join(case.assumptions_or_blockers),
            ]
        )
    return buffer.getvalue()


def render_traceability_csv(coverage: CoverageReport) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(
        [
            "requirement_id", "requirement_text", "data_quality_id", "data_quality_text",
            "test_case_ids", "automated_test_case_ids", "coverage_status", "reason",
        ]
    )
    for row in coverage.rows:
        writer.writerow(
            [
                row.requirement_id, row.requirement_text, row.data_quality_id,
                row.data_quality_text, "; ".join(row.test_case_ids),
                "; ".join(row.automated_test_case_ids), row.coverage_status.value, row.reason,
            ]
        )
    return buffer.getvalue()


# --------------------------------------------------------------------------
# Manifests
# --------------------------------------------------------------------------
def build_ticket_manifest(result: PipelineResult) -> dict:
    coverage = result.coverage
    snapshots = {s.table_name: s.row_count for s in result.snapshots}
    return {
        "pipeline_name": result.pipeline_name,
        "status": result.status.value,
        "source": result.source.value if result.source else None,
        "started_at": _stamp(result.started_at),
        "finished_at": _stamp(result.finished_at),
        "duration_seconds": result.duration_seconds,
        "snapshot_row_counts": snapshots,
        "counts": {
            "requirements": len(result.analysis.entities) if result.analysis else 0,
            "data_quality_rules": (
                len([e for e in result.analysis.entities if e.entity_type == "data_quality"])
                if result.analysis
                else 0
            ),
            "test_cases": len(result.test_cases.test_cases) if result.test_cases else 0,
            "automation_candidates": (
                len(
                    [
                        c
                        for c in result.test_cases.test_cases
                        if c.automation_candidate is not AutomationCandidate.NO
                    ]
                )
                if result.test_cases
                else 0
            ),
            "pytest_files": len(result.pytest.files) if result.pytest else 0,
        },
        "coverage": (
            {
                "requirement_coverage_pct": coverage.requirement_coverage_pct,
                "automation_pct": coverage.automation_pct,
                "covered_requirements": coverage.covered_requirements,
                "partially_covered_requirements": coverage.partially_covered_requirements,
                "uncovered_requirements": coverage.uncovered_requirements,
                "orphan_requirement_ids": coverage.orphan_requirement_ids,
                "orphan_test_case_ids": coverage.orphan_test_case_ids,
                "unknown_reference_ids": coverage.unknown_reference_ids,
            }
            if coverage
            else None
        ),
        "automation_readiness": (
            result.pytest.readiness.value if result.pytest else None
        ),
        "missing_information": (
            result.pytest.missing_information if result.pytest else []
        ),
        "warnings": result.warnings,
        "error": result.error,
        "artifacts": result.artifacts,
        "stages": [
            {
                "stage": s.stage.value,
                "status": s.status.value,
                "message": s.message,
                "duration_seconds": s.duration_seconds,
            }
            for s in result.stages
        ],
    }


def build_run_manifest(run: RunSummary) -> dict:
    return {
        "run_id": run.run_id,
        "generator": "Healthcare ETL QA Crew",
        "started_at": _stamp(run.started_at),
        "finished_at": _stamp(run.finished_at),
        "requested_pipelines": run.requested_pipelines,
        "invalid_inputs": run.invalid_inputs,
        "duplicates_removed": run.duplicates_removed,
        "totals": {
            "requested": len(run.requested_pipelines),
            "completed": len(run.completed),
            "completed_with_warnings": len(run.completed_with_warnings),
            "failed": len(run.failed),
        },
        "successful": run.successful,
        "pipelines": [build_ticket_manifest(r) for r in run.results],
    }


# --------------------------------------------------------------------------
# Writing to disk
# --------------------------------------------------------------------------
def write_ticket_artifacts(result: PipelineResult, run_dir: Path) -> dict[str, str]:
    """Write every artifact for one pipeline run. Returns ``{name: relative path}``."""
    pipeline_dir = run_dir / safe_path_segment(result.pipeline_name)
    pipeline_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    def _write(name: str, content: str, subdir: Path | None = None) -> None:
        target = (subdir or pipeline_dir) / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written[name] = str(target.relative_to(run_dir))

    if result.snapshots:
        snap_dir = pipeline_dir / "snapshots"
        snap_dir.mkdir(parents=True, exist_ok=True)
        for snapshot in result.snapshots:
            snap_dir.joinpath(f"{snapshot.table_name}.json").write_text(
                json.dumps(snapshot.model_dump(mode="json"), indent=2), encoding="utf-8"
            )
    if result.analysis:
        _write("schema_analysis.md", render_schema_analysis_md(result.analysis))
        _write(
            "schema_analysis.json",
            json.dumps(result.analysis.model_dump(mode="json"), indent=2),
        )
    if result.recon_plan:
        _write("reconciliation_strategy.md", render_recon_plan_md(result.recon_plan))
    if result.test_cases:
        _write("test_cases.md", render_test_cases_md(result.test_cases))
        _write("test_cases.csv", render_test_cases_csv(result.test_cases))
    if result.coverage:
        _write("traceability_matrix.csv", render_traceability_csv(result.coverage))
    if result.pytest:
        _write("pytest_automation.md", render_pytest_md(result.pytest))
        py_root = pipeline_dir / "pytest"
        for file in result.pytest.files:
            safe_parts = [safe_path_segment(p) for p in Path(file.path).parts]
            target = py_root.joinpath(*safe_parts)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(file.content, encoding="utf-8")
            written[file.path] = str(target.relative_to(run_dir))

    manifest = build_ticket_manifest(result)
    manifest["artifacts"] = dict(written)
    (pipeline_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    written["manifest.json"] = str((pipeline_dir / "manifest.json").relative_to(run_dir))

    result.artifact_dir = str(pipeline_dir)
    result.artifacts = written
    return written


def write_run_artifacts(run: RunSummary, output_dir: Path) -> Path:
    """Write the run-level summary and manifest, and return the run directory."""
    run_dir = output_dir / safe_path_segment(run.run_id)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "run_summary.md").write_text(render_run_summary_md(run), encoding="utf-8")
    (run_dir / "manifest.json").write_text(
        json.dumps(build_run_manifest(run), indent=2), encoding="utf-8"
    )
    run.output_dir = str(run_dir)
    return run_dir


# --------------------------------------------------------------------------
# ZIP
# --------------------------------------------------------------------------
def build_zip(run: RunSummary, pipelines: list[str] | None = None) -> bytes:
    """Bundle artifacts into a ZIP, built on demand rather than kept in memory.

    ``pipelines`` limits the bundle to specific pipeline names; the default is
    the whole run.
    """
    wanted = {p.strip().lower() for p in pipelines} if pipelines else None
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr(f"{run.run_id}/run_summary.md", render_run_summary_md(run))
        archive.writestr(
            f"{run.run_id}/manifest.json", json.dumps(build_run_manifest(run), indent=2)
        )
        for result in run.results:
            if wanted and result.pipeline_name.lower() not in wanted:
                continue
            if result.status is PipelineStatus.FAILED and not result.analysis:
                continue
            base = f"{run.run_id}/{safe_path_segment(result.pipeline_name)}"
            for name, content in _ticket_files(result):
                archive.writestr(f"{base}/{name}", content)

    buffer.seek(0)
    return buffer.getvalue()


def _ticket_files(result: PipelineResult) -> list[tuple[str, str]]:
    """The in-memory file list for one pipeline, rendered deterministically."""
    files: list[tuple[str, str]] = []
    if result.snapshots:
        for snapshot in result.snapshots:
            files.append(
                (
                    f"snapshots/{snapshot.table_name}.json",
                    json.dumps(snapshot.model_dump(mode="json"), indent=2),
                )
            )
    if result.analysis:
        files.append(("schema_analysis.md", render_schema_analysis_md(result.analysis)))
        files.append(
            (
                "schema_analysis.json",
                json.dumps(result.analysis.model_dump(mode="json"), indent=2),
            )
        )
    if result.recon_plan:
        files.append(("reconciliation_strategy.md", render_recon_plan_md(result.recon_plan)))
    if result.test_cases:
        files.append(("test_cases.md", render_test_cases_md(result.test_cases)))
        files.append(("test_cases.csv", render_test_cases_csv(result.test_cases)))
    if result.coverage:
        files.append(("traceability_matrix.csv", render_traceability_csv(result.coverage)))
    if result.pytest:
        files.append(("pytest_automation.md", render_pytest_md(result.pytest)))
        for file in result.pytest.files:
            safe = "/".join(safe_path_segment(p) for p in Path(file.path).parts)
            files.append((f"pytest/{safe}", file.content))
    files.append(("manifest.json", json.dumps(build_ticket_manifest(result), indent=2)))
    return files


# --------------------------------------------------------------------------
def _cell(text: str) -> str:
    """Make a string safe for a Markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _stamp(value: datetime | None) -> str | None:
    return value.isoformat(timespec="seconds") if value else None
